version: '3.8'

services:
  db:
    container_name: database
    image: "postgres:latest"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}     
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "54321:80"
    depends_on:
      - db
    
volumes:
  pgdata:
